title: সবার জন্য প্রোগ্রামিং - ব্লগ
author:
  name: HowToCode.dev
  email: ask@howtocode.dev
description: > # this means to ignore newlines until "show_excerpts:"
  বাংলাতেই শুরু হোক প্রোগ্রামিং শেখার যাত্রা
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  howtocode-dev
    # devto: jekyll
    # dribbble: jekyll
    facebook: howtocode.dev
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
